### ISSUE TITLE
Can you upload the video on bilibili?

### ISSUE THREAD

**Issue by Muyun99** [thuml/Self-Tuning#2]
The [video](https://icml.cc/virtual/2021/spotlight/8616) in ICML 2021 website is not available for the non-registered users.

So it will be very helpful if you can upload the video on bilibili, thanks!

![image](https://user-images.githubusercontent.com/27944418/127465253-5845d86c-8e9d-4bf0-96d7-bfeb940adb1c.png)

**Comment by wxm17** [comment]
The same video is available at SlidesLive but without subtitles.  The link is here. 

https://recorder-v3.slideslive.com/#/share?share=40334&s=f7988e61-bece-4a7a-a6ba-3e1a2b49b37b

**Comment by Muyun99** [comment]
Got it, thanks for your quick response!

However, i can`t open it normally. Do you have the same problem there?

![image](https://user-images.githubusercontent.com/27944418/127520162-c3ffade5-854e-4cc8-b11e-c4a48b178878.png)

**Comment by wxm17** [comment]
However,  I can open it normally. I also sent this link to my friends and they verified the accessibility of the video. Would you mind check it on other browsers or devices, e.g., on your mobile phone?

**Comment by Muyun99** [comment]
Thanks for your reply. This site can now be accessed normally.

Hope you can update the readme if possible.

Thx again for your reply!
