### ISSUE TITLE
Can Cifar100 uses the imagenet-pretrained model(efficientnet)? The resolution differs a lot.

### ISSUE THREAD

**Issue by shiyegao** [thuml/Self-Tuning#4]
You mention that you use Efficientnet for cifar100 in your paper. 
![image](https://user-images.githubusercontent.com/45991529/129648181-63352642-06da-4fbe-a3e7-d8b2ded5bdc4.png)

Your corresponding code is like
![image](https://user-images.githubusercontent.com/45991529/129648215-a5a9b9e8-bb42-401b-a819-26f0b333a54f.png)

Can Cifar100 uses the imagenet-pretrained model(efficientnet)? The resolution differs a lot.

I really appreciate it if you could answer my question!

**Comment by wxm17** [comment]
Yes. We resize the shape of cifar100 images to [224, 224]

def get_cifar100(args, root):
    transform_val = transforms.Compose([
        ResizeImage(size=224),
        transforms.ToTensor(),
        transforms.Normalize(mean=cifar100_mean, std=cifar100_std)])

class TransformTrainCifar(object):
    def __init__(self, mean, std, crop_size=224):
        self.strong = transforms.Compose([
            transforms.RandomHorizontalFlip(),
            transforms.RandomCrop(size=32,
                                  padding=int(32*0.125),
                                  padding_mode='reflect'),
            RandAugmentMC(n=2, m=10),
            ResizeImage(size=crop_size),
        ])
        self.normalize = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=mean, std=std)])

    def __call__(self, x):
        return [self.normalize(self.strong(x)) for _ in range(2)]
