### ISSUE TITLE
No module named 'efficientnet_pytorch'

### ISSUE THREAD

**Issue by Fanyan-0411** [thuml/Self-Tuning#7]
No module or files named 'efficientnet_pytorch' in the whole file holder. But 'from efficientnet_pytorch import EfficientNet' appears in the first line of efficientnet.py
Is there any thing should be done before running main.py? Thanks for your reply!

**Comment by wxm17** [comment]
You can easily install it by running *pip install efficientnet_pytorch* as shown in https://github.com/lukemelas/EfficientNet-PyTorch
